### PR TITLE
feat: update Orderly with addresses.yaml file.

### PR DESCRIPTION
**Pull request by joooeoeee**
### Description

 Update Orderly with addresses.yaml file: I wanted to create Warp Routes to Orderly but I couldn't find the mailbox address.

### Backward compatibility

 No.

### Testing

 yes, CLI.

### CODE REVIEW

**Review by paulbalaji — CHANGES_REQUESTED** [review]
you need to change the deployer details in the metadata

**Comment by joooeoeee** [comment]
Hello Paul, it's done

**Review by joooeoeee — COMMENTED** [review]
Deployer information updated.

**Comment by paulbalaji** [comment]
> Deployer information updated.
> 
> @paulbalaji, I understand you have a heavy workload, but please let me know if there are any additional details you'd need from my side to move this PR forward.

Sorry for not updating you sooner! We're deploying to this network as part of our latest batch of chains, so will have to close this PR for now. You can view this draft PR for the latest addresses: https://github.com/hyperlane-xyz/hyperlane-registry/pull/336/files#diff-431d022871d839baabe089e7adc6a36520fe56fb5b69840371b97a351f3b67ed

**Comment by joooeoeee** [comment]
> > Deployer information updated.
> > @paulbalaji, I understand you have a heavy workload, but please let me know if there are any additional details you'd need from my side to move this PR forward.
> 
> Sorry for not updating you sooner! We're deploying to this network as part of our latest batch of chains, so will have to close this PR for now. You can view this draft PR for the latest addresses: https://github.com/hyperlane-xyz/hyperlane-registry/pull/336/files#diff-431d022871d839baabe089e7adc6a36520fe56fb5b69840371b97a351f3b67ed

**Comment by joooeoeee** [comment]
Thanks Paul, I understand.
PR Closed

**Pull request closed without merging**
