### PR TITLE
feat: add Boba BNB

### PR DESCRIPTION
**Pull request by boyuan-chen**
### Description

Add Boba BNB

### Testing

```
~/.hyperlane/chains/boba main* ❯ hyperlane send message --relay                                                                   3m 15s 01:43:55 PM
Hyperlane CLI
? Select network type Testnet
? Select the origin chain holesky
? Select network type Mainnet
? Select the destination chain bobabnb
Running pre-flight checks for chains...
✅ Chains are valid
✅ Signer is valid
✅ Balances are sufficient
Dispatching message
Pending https://holesky.etherscan.io/tx/0x206d72f2395f76b465f7c522cc40108f523b8c223579a77ecc1c60b348eee134 (waiting 1 blocks for confirmation)
Sent message from holesky to 0xfe52E6569d642ef246d8252964aeCd158C169308 on bobabnb.
Message ID: 0x19611555182dc816766abff4d623525e240f2e3589f95c29d65de21a1f7df85f
Message:
    parsed:
      version: 3
      nonce: 418
      origin: 17000
      sender: "0x000000000000000000000000239cd87712b2cb0c35f1deaf4fb68b8f9585e9d1"
      destination: 56288
      recipient: "0x000000000000000000000000fe52e6569d642ef246d8252964aecd158c169308"
      body: "0x48656c6c6f21"
      originChain: holesky
      destinationChain: bobabnb
    id: "0x19611555182dc816766abff4d623525e240f2e3589f95c29d65de21a1f7df85f"
    message: "0x03000001a200004268000000000000000000000000239cd87712b2cb0c35f1deaf4\
      fb68b8f9585e9d10000dbe0000000000000000000000000fe52e6569d642ef246d8252964aecd\
      158c16930848656c6c6f21"

Unhandled error case in combined provider error handler
Unhandled error case in combined provider error handler
Unhandled error case in combined provider error handler
Attempting self-relay of message
Preparing to relay message 0x19611555182dc816766abff4d623525e240f2e3589f95c29d65de21a1f7df85f
Unhandled error case in combined provider error handler
Unhandled error case in combined provider error handler
Unhandled error case in combined provider error handler
{
  message: {
    id: '0x19611555182dc816766abff4d623525e240f2e3589f95c29d65de21a1f7df85f',
    message: '0x03000001a200004268000000000000000000000000239cd87712b2cb0c35f1deaf4fb68b8f9585e9d10000dbe0000000000000000000000000fe52e6569d642ef246d8252964aecd158c16930848656c6c6f21',
    parsed: {
      version: 3,
      nonce: 418,
      origin: 17000,
      sender: '0x000000000000000000000000239cd87712b2cb0c35f1deaf4fb68b8f9585e9d1',
      destination: 56288,
      recipient: '0x000000000000000000000000fe52e6569d642ef246d8252964aecd158c169308',
      body: '0x48656c6c6f21'
    }
  },
  metadata: '0x'
} Relaying message 0x19611555182dc816766abff4d623525e240f2e3589f95c29d65de21a1f7df85f
Pending https://bobascan.com/tx/0xa438b7806318c86d4abc349ef243c17dc009374f859711f9bf182eb4a4c79dc9 (waiting 1 blocks for confirmation)
Message was self-relayed!
```

### CODE REVIEW

**Review by xeno097 — CHANGES_REQUESTED** [review]
Hey @boyuan-chen thank you for another pr to the Hyperlane Registry! As in the other PR the changeset is missing here too. Please add one

**Comment by boyuan-chen** [comment]
> Hey @boyuan-chen thank you for another pr to the Hyperlane Registry! As in the other PR the changeset is missing here too. Please add one

Added!

**Review by xeno097 — CHANGES_REQUESTED** [review]
Hey @boyuan-chen can you run `yarn prettier` to fix the ci failure and then run `yarn lint:fix` to verify that the issue has been fixed? After this this PR should be ready to be merged

**Comment by boyuan-chen** [comment]
> Hey @boyuan-chen can you run `yarn prettier` to fix the ci failure and then run `yarn lint:fix` to verify that the issue has been fixed? After this this PR should be ready to be merged

Fixed!

**Pull request merged**
