### PR TITLE
feat: deploy to cheesechain and add USDC Collateral Vault

### PR DESCRIPTION
**Pull request by rshtirmer**
- Added CheeseChain
- Added USDC collateral vault powered by https://app.morpho.org/vault?vault=0xdd0f28e19C1780eb6396170735D45153D261490d&network=mainnet
- Example Deposit: https://etherscan.io/tx/0xe74758fcb89113460c39d80c1f9a9c87f8070ce6d00fe3f67cb9293fb63c358e

### CODE REVIEW

**Comment by jmrossy** [comment]
@rshtirmer Looks like the lint is failing because the keys aren't alphabetically ordered. This can be fixed by running `yarn lint:fix`. Also you need a changeset. I've made a PR to add one for you

**Comment by rshtirmer** [comment]
> @rshtirmer Looks like the lint is failing because the keys aren't alphabetically ordered. This can be fixed by running `yarn lint:fix`. Also you need a changeset. I've made a PR to add one for you

Thank you @jmrossy! I pushed the linted update, will check back in on Monday to see if there's anything else.

**Comment by jmrossy** [comment]
@rshtirmer The PR also needs a changeset. I've opened a PR against your branch to add one for you

**Comment by rshtirmer** [comment]
> @rshtirmer The PR also needs a changeset. I've opened a PR against your branch to add one for you

Thanks! I commited the changeset to the PR branch.

**Review by jmrossy — APPROVED** [review]

**Pull request merged**
